(function () {
	var obj = {
		NoTableData: "Table {1} no data",
		NoBindingTableData: "Table {2} does not have data assoicated with component {1}",
		NoPrintTemplateDefined: "Print template undefined with form {1}",
		CircleDependency: "Circle dependency exists in form {1}",
		GridExpandOrGroupInGridPage: "No page limited with grid expand or group",
		ExistGroupRowInGridPage: "No group row limited in grid page",
		DefaultFormulaValueExistBothInCellAndEmb: "Formula exists both in cell and subdetail component",
		OuterColumnMustBeTitle: "Outermost column must be with type title",
		UndefinedPageLoadType: "Page type undefined!",
		UnableToGetCellBehavior: "Unable to get dynamic behavior!",
		CheckRuleNotPass: "{1} check rule not pass!",
		EmbedSubBindingError: "SubDetail binding error",
		FormulaIdentifierError: "Formula identifier error",
		DataBindingError: "Data binding error,Datasource not found",
		NoRowSelected: "No selected row",
		SequenceNoDefine: "Sequence column undefined",
		LayerOrHiddenNoDefine: "Configuration error,Layer column and Hidden column must be coexists!",
		ShowLayerDataNotAllowGridExpand: "Column expand unsupported with data layer",
		RequiredError: "{1} cannot be null",
		NoComponentFound: "Undefined copmonent",
		ForeignFieldsInequality: "Source fields and target fields not consistent",
		NoTableFound: "Table not found",
		NoEmptyRowFound: "No empty row found in target grid",
		GridTreeColumnDefineError: "Undefined Tree column type",
		UndefinedRowExpandType: "Undefined row expand type",
		RefOperationNotDefined: "Reference operation {2} ont exists in form {1}",
		NoDetailRowDefine: "Detail row undefined",
		ComponentNotExists: "{1} not exists",
		NoRefDetailTableKeyDefine: "RefDetailTableKey undefined",
		NoRefTableKeyDefine: "RefTableKey undefined",
		NoExpandSourceGet: "No result with column expand source",
		UndefinedSubDetailLinkType: "Undefined subdetail type",
		NoSubDetailsInEmptyRow: "Please edit grid first",
		NoGridOrListViewFound: "Grid or ListView not exists",
		CellMergeDefineError: "Cell merge error with different row type",
		SourceTypeDefineError: "Source type define error",
		
		NoCellCannotSetValue: "Cannot set value without a cell",
		CannnotGetNoCellValue: "Cannot get value without a cell",
		CompdictCannotSetMultidict: "Compdict {1} cannot be multiselect",
		DynamicdictItemkeyNull: "Dynamicdict {1} itemkey cannot be null",
		CompdictItemkeyNull: "Compdict {1} itemkey is null",
		NoComponent: "Component {1} undefined",
		NoWidthOrHeight: "Width or Height undefined",
		NoKeyTargetBill: "Target bill's key is null",
		ExceedValueMaxAccuracy: "Exceed the maximum accuracy",
		DateDiffParamError: "Function DateDiff parameter error",
		NoComponentKey: "Component {1} not exists",
		NeedPrimarysDefined: "Grid primary key needed without OID column in paging",
		TypeFormulaNeeded: "Type formula needed with dynamic cell",
		TypeGroupUnDefined: "Dynamic cell group defined in form {1}",
		TypeDefUnDefined: "Dynamic configuration undefined with key {1}",
		TypeDefKeyColumnUndefined: "Dynamic column undefined with key {1}",
		TypeDefKeyEmpty: "Type key not found in grid data",
		UnknownDetailType: "Unknown detail type",
		ExpandSourceUndefined: "Grid column {1} expand source undefined",
		ExpandColumnKeyUndefined: "Grid column {1} expand column key undefined",
		ViewFormOnly: "Function {1} only suitable for use in form with type view",
		DeleteRowWithSubDetail: "Delete row with detail data ?",
		DeleteRowWithChildRows: "Delete row with children rows ?",
		DeleteAllSelectRows: "Delete all select rows ?",
		ConfirmClose: "Are you sure to close the form ?",
		UnSupportRowExpandType: "Unsupport row expand type {1}",
		NoEntryRights: "No entry rights {1}",
		ListViewNotFound: "ListView not found in view form",
		ItemKeyColumnUndefined: "Dynamic Dict or Complex Dict {1} ItemKey column undefined",
		DictDataError: "Dict {1} data type error,normal dict should be long,and dict allow multiselection is String",
		AttachmentExceedMaxSize: "Attachment exceed max size {1}KB",
		ConnectFailed: "Server connect failed,Please check your network and try again!",
		FormCheckError: "Error in form {1}",
		GridRowError: "Error in grid {1}, line no {2}",
		GridCellError: "Error in grid {1}, line no {2}, cell key {3}",
		GridCellRequired: "grid {1}, line no {2}, cell {3} cannot be null",
		
		VeCannotNull: "Ve can't be null",
		NoLoadHandlerClass: "{1} No load handler class",
		DictRootNodeCalcError: "Dict root node calculation error",
		ItemkeyNotAgreeWithCurrent: "Dict root node itemKey[{1}] not agree with the current itemKey[{2}]",
		ItemkeyNoCompDict: "Itemkey:{1} not compdict",
		NoDict: "Dict ItemKey:{1} is no",
		NoComponentBuilderClass: "{1},{2} no component builder class",
		UnitNotSupportType: "IUnitConverter not support type: {1}",
		NotSupportType: "not support type: {1}",
		DictInputValueTypeError: "Dict input value type error:{1}",
		TimeError: "Time error:{1}",
		filterDependenceUntreatedType: "filterDependence Type:{1} of Untreated",
		CompdictNotDataBinding: "Compdict:{1} no data binding field",
		UnEqualParamNum: "{1} Parameter Number Inconsistent",
		AttachmentTypeError: "Attachment type {1} error",
		RadioButtonNoGroupKey: "RadioButton {1} GroupKey undefined"
	}

	if(YIUI.StringTable.View) {
		YIUI.StringTable.View = $.extend(YIUI.StringTable.View, obj);
	} else {
		YIUI.StringTable.View = $.extend(YIUI.StringTable, obj);
	}

})();
	
